/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as BidderContractJson } from "../Bidder.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";

// Custom types for the contract
export namespace BidderTypes {
  export type Fields = {
    auction: HexString;
    address: Address;
    bidAmount: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getAddress: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<Address>;
    };
    rebid: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    withdraw: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    auctionEnd: {
      params: CallContractParams<{ to: Address; amount: bigint }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getAddress: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    rebid: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    withdraw: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    auctionEnd: {
      params: SignExecuteContractMethodParams<{ to: Address; amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<BidderInstance, BidderTypes.Fields> {
  encodeFields(fields: BidderTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  consts = { InvalidCaller: BigInt("0") };

  at(address: string): BidderInstance {
    return new BidderInstance(address);
  }

  tests = {
    getAddress: async (
      params: Omit<
        TestContractParamsWithoutMaps<BidderTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<Address>> => {
      return testMethod(this, "getAddress", params, getContractByCodeHash);
    },
    rebid: async (
      params: TestContractParamsWithoutMaps<
        BidderTypes.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "rebid", params, getContractByCodeHash);
    },
    withdraw: async (
      params: Omit<
        TestContractParamsWithoutMaps<BidderTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "withdraw", params, getContractByCodeHash);
    },
    auctionEnd: async (
      params: TestContractParamsWithoutMaps<
        BidderTypes.Fields,
        { to: Address; amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "auctionEnd", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: BidderTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const Bidder = new Factory(
  Contract.fromJson(
    BidderContractJson,
    "",
    "385c3393bd0c93fa75175b8945a77006db3cc1d51613637920b331638992a81b",
    []
  )
);
registerContract(Bidder);

// Use this class to interact with the blockchain
export class BidderInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<BidderTypes.State> {
    return fetchContractState(Bidder, this);
  }

  view = {
    getAddress: async (
      params?: BidderTypes.CallMethodParams<"getAddress">
    ): Promise<BidderTypes.CallMethodResult<"getAddress">> => {
      return callMethod(
        Bidder,
        this,
        "getAddress",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    rebid: async (
      params: BidderTypes.CallMethodParams<"rebid">
    ): Promise<BidderTypes.CallMethodResult<"rebid">> => {
      return callMethod(Bidder, this, "rebid", params, getContractByCodeHash);
    },
    withdraw: async (
      params?: BidderTypes.CallMethodParams<"withdraw">
    ): Promise<BidderTypes.CallMethodResult<"withdraw">> => {
      return callMethod(
        Bidder,
        this,
        "withdraw",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    auctionEnd: async (
      params: BidderTypes.CallMethodParams<"auctionEnd">
    ): Promise<BidderTypes.CallMethodResult<"auctionEnd">> => {
      return callMethod(
        Bidder,
        this,
        "auctionEnd",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getAddress: async (
      params: BidderTypes.SignExecuteMethodParams<"getAddress">
    ): Promise<BidderTypes.SignExecuteMethodResult<"getAddress">> => {
      return signExecuteMethod(Bidder, this, "getAddress", params);
    },
    rebid: async (
      params: BidderTypes.SignExecuteMethodParams<"rebid">
    ): Promise<BidderTypes.SignExecuteMethodResult<"rebid">> => {
      return signExecuteMethod(Bidder, this, "rebid", params);
    },
    withdraw: async (
      params: BidderTypes.SignExecuteMethodParams<"withdraw">
    ): Promise<BidderTypes.SignExecuteMethodResult<"withdraw">> => {
      return signExecuteMethod(Bidder, this, "withdraw", params);
    },
    auctionEnd: async (
      params: BidderTypes.SignExecuteMethodParams<"auctionEnd">
    ): Promise<BidderTypes.SignExecuteMethodResult<"auctionEnd">> => {
      return signExecuteMethod(Bidder, this, "auctionEnd", params);
    },
  };

  async multicall<Calls extends BidderTypes.MultiCallParams>(
    calls: Calls
  ): Promise<BidderTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends BidderTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<BidderTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends BidderTypes.MultiCallParams | BidderTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(Bidder, this, callss, getContractByCodeHash);
  }
}
