/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  SubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as BidderContractJson } from "../Bidder.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace BidderTypes {
  export type Fields = {
    auction: HexString;
    address: Address;
    bidAmount: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getAddress: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<Address>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<BidderInstance, BidderTypes.Fields> {
  consts = { InvalidCaller: BigInt(0) };

  at(address: string): BidderInstance {
    return new BidderInstance(address);
  }

  tests = {
    getAddress: async (
      params: Omit<TestContractParams<BidderTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<Address>> => {
      return testMethod(this, "getAddress", params);
    },
    rebid: async (
      params: TestContractParams<BidderTypes.Fields, { amount: bigint }>
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "rebid", params);
    },
    withdraw: async (
      params: Omit<TestContractParams<BidderTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "withdraw", params);
    },
    auctionEnd: async (
      params: TestContractParams<
        BidderTypes.Fields,
        { to: Address; amount: bigint }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "auctionEnd", params);
    },
  };
}

// Use this object to test and deploy the contract
export const Bidder = new Factory(
  Contract.fromJson(
    BidderContractJson,
    "",
    "0f31c5db9706970d0f12be335dd9837f0e7c9ec257f4b64f668207aa449ae6ce"
  )
);

// Use this class to interact with the blockchain
export class BidderInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<BidderTypes.State> {
    return fetchContractState(Bidder, this);
  }

  methods = {
    getAddress: async (
      params?: BidderTypes.CallMethodParams<"getAddress">
    ): Promise<BidderTypes.CallMethodResult<"getAddress">> => {
      return callMethod(
        Bidder,
        this,
        "getAddress",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  async multicall<Calls extends BidderTypes.MultiCallParams>(
    calls: Calls
  ): Promise<BidderTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      Bidder,
      this,
      calls,
      getContractByCodeHash
    )) as BidderTypes.MultiCallResults<Calls>;
  }
}
