/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as AuctionContractJson } from "../Auction.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { Bid, AllStructs } from "./types";
import { RalphMap } from "@alephium/web3";

// Custom types for the contract
export namespace AuctionTypes {
  export type Fields = {
    beneficiary: Address;
    biddingEnd: bigint;
    revealEnd: bigint;
    ended: boolean;
    highestBidder: Address;
    highestBid: bigint;
  };

  export type State = ContractState<Fields>;

  export type AuctionEndedEvent = ContractEvent<{
    winner: Address;
    amount: bigint;
  }>;

  export interface CallMethodTable {
    bid: {
      params: CallContractParams<{
        bidder: Address;
        blindedBid: HexString;
        deposit: bigint;
      }>;
      result: CallContractResult<null>;
    };
    reveal: {
      params: CallContractParams<{
        bidder: Address;
        values: HexString;
        fakes: HexString;
        secrets: HexString;
      }>;
      result: CallContractResult<null>;
    };
    auctionEnd: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    getBidNum: {
      params: CallContractParams<{ bidder: Address }>;
      result: CallContractResult<bigint>;
    };
    getBid: {
      params: CallContractParams<{ bidder: Address; index: bigint }>;
      result: CallContractResult<Bid>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    bid: {
      params: SignExecuteContractMethodParams<{
        bidder: Address;
        blindedBid: HexString;
        deposit: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    reveal: {
      params: SignExecuteContractMethodParams<{
        bidder: Address;
        values: HexString;
        fakes: HexString;
        secrets: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
    auctionEnd: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getBidNum: {
      params: SignExecuteContractMethodParams<{ bidder: Address }>;
      result: SignExecuteScriptTxResult;
    };
    getBid: {
      params: SignExecuteContractMethodParams<{
        bidder: Address;
        index: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];

  export type Maps = {
    bids?: Map<HexString, Bid>;
    bidNum?: Map<Address, bigint>;
  };
}

class Factory extends ContractFactory<AuctionInstance, AuctionTypes.Fields> {
  encodeFields(fields: AuctionTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  eventIndex = { AuctionEnded: 0 };
  consts = {
    ErrorCodes: {
      InvalidArg: BigInt("0"),
      BiddingAlreadyEnded: BigInt("1"),
      InvalidBidderAddress: BigInt("2"),
      BiddingNotEnd: BigInt("3"),
      RevealAlreadyEnded: BigInt("4"),
      RevealNotEnd: BigInt("5"),
      AuctionEndAlreadyCalled: BigInt("6"),
    },
  };

  at(address: string): AuctionInstance {
    return new AuctionInstance(address);
  }

  tests = {
    bid: async (
      params: TestContractParams<
        AuctionTypes.Fields,
        { bidder: Address; blindedBid: HexString; deposit: bigint },
        AuctionTypes.Maps
      >
    ): Promise<TestContractResult<null, AuctionTypes.Maps>> => {
      return testMethod(this, "bid", params, getContractByCodeHash);
    },
    reveal: async (
      params: TestContractParams<
        AuctionTypes.Fields,
        {
          bidder: Address;
          values: HexString;
          fakes: HexString;
          secrets: HexString;
        },
        AuctionTypes.Maps
      >
    ): Promise<TestContractResult<null, AuctionTypes.Maps>> => {
      return testMethod(this, "reveal", params, getContractByCodeHash);
    },
    auctionEnd: async (
      params: Omit<
        TestContractParams<AuctionTypes.Fields, never, AuctionTypes.Maps>,
        "args"
      >
    ): Promise<TestContractResult<null, AuctionTypes.Maps>> => {
      return testMethod(this, "auctionEnd", params, getContractByCodeHash);
    },
    getBidNum: async (
      params: TestContractParams<
        AuctionTypes.Fields,
        { bidder: Address },
        AuctionTypes.Maps
      >
    ): Promise<TestContractResult<bigint, AuctionTypes.Maps>> => {
      return testMethod(this, "getBidNum", params, getContractByCodeHash);
    },
    getBid: async (
      params: TestContractParams<
        AuctionTypes.Fields,
        { bidder: Address; index: bigint },
        AuctionTypes.Maps
      >
    ): Promise<TestContractResult<Bid, AuctionTypes.Maps>> => {
      return testMethod(this, "getBid", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: AuctionTypes.Fields,
    asset?: Asset,
    address?: string,
    maps?: AuctionTypes.Maps
  ) {
    return this.stateForTest_(initFields, asset, address, maps);
  }
}

// Use this object to test and deploy the contract
export const Auction = new Factory(
  Contract.fromJson(
    AuctionContractJson,
    "=6-4+e=1-1=2-2+80=2-1=1+5=2-2+de4313=12-2+52=95-1+b=34+7a7e0214696e73657274206174206d617020706174683a2000=128+7a7e0214696e73657274206174206d617020706174683a2000=91-1+b=177-1+4=57-1+f=225-1+c=136+7a7e021472656d6f7665206174206d617020706174683a2000=51-1+8=21-1+b=38+7a7e021472656d6f7665206174206d617020706174683a2000=300",
    "663fb20ed6c02ed38c1a0ac4bbaba391cc396e23a218896d2b2351e1fa174c66",
    AllStructs
  )
);
registerContract(Auction);

// Use this class to interact with the blockchain
export class AuctionInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  maps = {
    bids: new RalphMap<HexString, Bid>(
      Auction.contract,
      this.contractId,
      "bids"
    ),
    bidNum: new RalphMap<Address, bigint>(
      Auction.contract,
      this.contractId,
      "bidNum"
    ),
  };

  async fetchState(): Promise<AuctionTypes.State> {
    return fetchContractState(Auction, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeAuctionEndedEvent(
    options: EventSubscribeOptions<AuctionTypes.AuctionEndedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Auction.contract,
      this,
      options,
      "AuctionEnded",
      fromCount
    );
  }

  view = {
    bid: async (
      params: AuctionTypes.CallMethodParams<"bid">
    ): Promise<AuctionTypes.CallMethodResult<"bid">> => {
      return callMethod(Auction, this, "bid", params, getContractByCodeHash);
    },
    reveal: async (
      params: AuctionTypes.CallMethodParams<"reveal">
    ): Promise<AuctionTypes.CallMethodResult<"reveal">> => {
      return callMethod(Auction, this, "reveal", params, getContractByCodeHash);
    },
    auctionEnd: async (
      params?: AuctionTypes.CallMethodParams<"auctionEnd">
    ): Promise<AuctionTypes.CallMethodResult<"auctionEnd">> => {
      return callMethod(
        Auction,
        this,
        "auctionEnd",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getBidNum: async (
      params: AuctionTypes.CallMethodParams<"getBidNum">
    ): Promise<AuctionTypes.CallMethodResult<"getBidNum">> => {
      return callMethod(
        Auction,
        this,
        "getBidNum",
        params,
        getContractByCodeHash
      );
    },
    getBid: async (
      params: AuctionTypes.CallMethodParams<"getBid">
    ): Promise<AuctionTypes.CallMethodResult<"getBid">> => {
      return callMethod(Auction, this, "getBid", params, getContractByCodeHash);
    },
  };

  transact = {
    bid: async (
      params: AuctionTypes.SignExecuteMethodParams<"bid">
    ): Promise<AuctionTypes.SignExecuteMethodResult<"bid">> => {
      return signExecuteMethod(Auction, this, "bid", params);
    },
    reveal: async (
      params: AuctionTypes.SignExecuteMethodParams<"reveal">
    ): Promise<AuctionTypes.SignExecuteMethodResult<"reveal">> => {
      return signExecuteMethod(Auction, this, "reveal", params);
    },
    auctionEnd: async (
      params: AuctionTypes.SignExecuteMethodParams<"auctionEnd">
    ): Promise<AuctionTypes.SignExecuteMethodResult<"auctionEnd">> => {
      return signExecuteMethod(Auction, this, "auctionEnd", params);
    },
    getBidNum: async (
      params: AuctionTypes.SignExecuteMethodParams<"getBidNum">
    ): Promise<AuctionTypes.SignExecuteMethodResult<"getBidNum">> => {
      return signExecuteMethod(Auction, this, "getBidNum", params);
    },
    getBid: async (
      params: AuctionTypes.SignExecuteMethodParams<"getBid">
    ): Promise<AuctionTypes.SignExecuteMethodResult<"getBid">> => {
      return signExecuteMethod(Auction, this, "getBid", params);
    },
  };

  async multicall<Calls extends AuctionTypes.MultiCallParams>(
    calls: Calls
  ): Promise<AuctionTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends AuctionTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<AuctionTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends AuctionTypes.MultiCallParams | AuctionTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(Auction, this, callss, getContractByCodeHash);
  }
}
