/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  SubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as BidderContractJson } from "../Bidder.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace BidderTypes {
  export type Fields = {
    blindedBidTemplateId: HexString;
    auction: HexString;
    address: Address;
    blindedBidSize: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getAddress: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<Address>;
    };
    reveal: {
      params: CallContractParams<{
        values: HexString;
        fakes: HexString;
        secrets: HexString;
        highestBid: bigint;
      }>;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<BidderInstance, BidderTypes.Fields> {
  consts = { ErrorCodes: { InvalidArg: BigInt(0), InvalidCaller: BigInt(1) } };

  at(address: string): BidderInstance {
    return new BidderInstance(address);
  }

  tests = {
    getAddress: async (
      params: Omit<TestContractParams<BidderTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<Address>> => {
      return testMethod(this, "getAddress", params);
    },
    bid: async (
      params: TestContractParams<
        BidderTypes.Fields,
        { blindedBid: HexString; amount: bigint }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "bid", params);
    },
    reveal: async (
      params: TestContractParams<
        BidderTypes.Fields,
        {
          values: HexString;
          fakes: HexString;
          secrets: HexString;
          highestBid: bigint;
        }
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "reveal", params);
    },
    withdraw_: async (
      params: Omit<TestContractParams<BidderTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "withdraw_", params);
    },
    withdraw: async (
      params: Omit<TestContractParams<BidderTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "withdraw", params);
    },
    auctionEnd: async (
      params: TestContractParams<
        BidderTypes.Fields,
        { to: Address; amount: bigint }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "auctionEnd", params);
    },
  };
}

// Use this object to test and deploy the contract
export const Bidder = new Factory(
  Contract.fromJson(
    BidderContractJson,
    "",
    "2aee42fa9a9e6118a48247cdc4707d864c25a3e741791d07966cdd7a586d73d1"
  )
);

// Use this class to interact with the blockchain
export class BidderInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<BidderTypes.State> {
    return fetchContractState(Bidder, this);
  }

  methods = {
    getAddress: async (
      params?: BidderTypes.CallMethodParams<"getAddress">
    ): Promise<BidderTypes.CallMethodResult<"getAddress">> => {
      return callMethod(
        Bidder,
        this,
        "getAddress",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    reveal: async (
      params: BidderTypes.CallMethodParams<"reveal">
    ): Promise<BidderTypes.CallMethodResult<"reveal">> => {
      return callMethod(Bidder, this, "reveal", params, getContractByCodeHash);
    },
  };

  async multicall<Calls extends BidderTypes.MultiCallParams>(
    calls: Calls
  ): Promise<BidderTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      Bidder,
      this,
      calls,
      getContractByCodeHash
    )) as BidderTypes.MultiCallResults<Calls>;
  }
}
