/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { getContractByCodeHash } from "./contracts";
import { default as NewBidScriptJson } from "../NewBid.ral.json";
import { Bid, AllStructs } from "./types";

export const NewBid = new ExecutableScript<{
  auction: HexString;
  blindedBid: HexString;
  amount: bigint;
}>(Script.fromJson(NewBidScriptJson, "", AllStructs), getContractByCodeHash);
