/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Address, HexString, Val, Struct, Contract } from "@alephium/web3";

import { default as allStructsJson } from "../structs.ral.json";
export const AllStructs = allStructsJson.map((json) => Struct.fromJson(json));

export interface Bid extends Record<string, Val> {
  blindedBid: HexString;
  deposit: bigint;
}
