/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  SubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as NewCodeContractJson } from "../NewCode.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace NewCodeTypes {
  export type Fields = {
    n: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    get: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    set: {
      params: CallContractParams<{ m: bigint }>;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<NewCodeInstance, NewCodeTypes.Fields> {
  at(address: string): NewCodeInstance {
    return new NewCodeInstance(address);
  }

  tests = {
    get: async (
      params: Omit<TestContractParams<NewCodeTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "get", params);
    },
    set: async (
      params: TestContractParams<NewCodeTypes.Fields, { m: bigint }>
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "set", params);
    },
  };
}

// Use this object to test and deploy the contract
export const NewCode = new Factory(
  Contract.fromJson(
    NewCodeContractJson,
    "",
    "16ef550a08d9e4991afd5af65516e28bd52f408260de4c1b3d331edd59d68288"
  )
);

// Use this class to interact with the blockchain
export class NewCodeInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<NewCodeTypes.State> {
    return fetchContractState(NewCode, this);
  }

  methods = {
    get: async (
      params?: NewCodeTypes.CallMethodParams<"get">
    ): Promise<NewCodeTypes.CallMethodResult<"get">> => {
      return callMethod(
        NewCode,
        this,
        "get",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    set: async (
      params: NewCodeTypes.CallMethodParams<"set">
    ): Promise<NewCodeTypes.CallMethodResult<"set">> => {
      return callMethod(NewCode, this, "set", params, getContractByCodeHash);
    },
  };

  async multicall<Calls extends NewCodeTypes.MultiCallParams>(
    calls: Calls
  ): Promise<NewCodeTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      NewCode,
      this,
      calls,
      getContractByCodeHash
    )) as NewCodeTypes.MultiCallResults<Calls>;
  }
}
