/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { getContractByCodeHash } from "./contracts";
import { default as MigrateWithFieldsScriptJson } from "../MigrateWithFields.ral.json";
import { default as NewGetScriptJson } from "../NewGet.ral.json";
import { default as NewSetScriptJson } from "../NewSet.ral.json";
import { default as OldGetScriptJson } from "../OldGet.ral.json";

export const MigrateWithFields = new ExecutableScript<{
  contract: HexString;
  newCode: HexString;
  newN: bigint;
}>(Script.fromJson(MigrateWithFieldsScriptJson, "", []), getContractByCodeHash);

export const NewGet = new ExecutableScript<{
  contract: HexString;
  expected: bigint;
}>(Script.fromJson(NewGetScriptJson, "", []), getContractByCodeHash);

export const NewSet = new ExecutableScript<{
  contract: HexString;
  newN: bigint;
}>(Script.fromJson(NewSetScriptJson, "", []), getContractByCodeHash);

export const OldGet = new ExecutableScript<{
  contract: HexString;
  expected: bigint;
}>(Script.fromJson(OldGetScriptJson, "", []), getContractByCodeHash);
