version: "3.8"
services:
  devnet:
    image: alephium/dev-env:latest
    container_name: alephium-devnet
    ports:
      - "22973:22973"
      - "127.0.0.1:15973:15973"
    environment:
      - ALEPHIUM_NETWORK=devnet
      - ALEPHIUM_MINING_THREADS=1
    volumes:
      - ./.devnet:/root/.alephium
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:22973/infos/version"]
      interval: 10s
      timeout: 5s
      retries: 5
