/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as DynamicArrayForLongContractJson } from "../DynamicArrayForLong.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace DynamicArrayForLongTypes {
  export type State = Omit<ContractState<any>, "fields">;

  export interface CallMethodTable {
    get: {
      params: CallContractParams<{ array: HexString; index: bigint }>;
      result: CallContractResult<bigint>;
    };
    update: {
      params: CallContractParams<{
        array: HexString;
        index: bigint;
        value: bigint;
      }>;
      result: CallContractResult<HexString>;
    };
    push: {
      params: CallContractParams<{ array: HexString; value: bigint }>;
      result: CallContractResult<HexString>;
    };
    pop: {
      params: CallContractParams<{ array: HexString }>;
      result: CallContractResult<HexString>;
    };
    sum: {
      params: CallContractParams<{ array: HexString }>;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<DynamicArrayForLongInstance, {}> {
  at(address: string): DynamicArrayForLongInstance {
    return new DynamicArrayForLongInstance(address);
  }

  tests = {
    get: async (
      params: Omit<
        TestContractParams<never, { array: HexString; index: bigint }>,
        "initialFields"
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "get", params);
    },
    update: async (
      params: Omit<
        TestContractParams<
          never,
          { array: HexString; index: bigint; value: bigint }
        >,
        "initialFields"
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "update", params);
    },
    push: async (
      params: Omit<
        TestContractParams<never, { array: HexString; value: bigint }>,
        "initialFields"
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "push", params);
    },
    pop: async (
      params: Omit<
        TestContractParams<never, { array: HexString }>,
        "initialFields"
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "pop", params);
    },
    sum: async (
      params: Omit<
        TestContractParams<never, { array: HexString }>,
        "initialFields"
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "sum", params);
    },
  };
}

// Use this object to test and deploy the contract
export const DynamicArrayForLong = new Factory(
  Contract.fromJson(
    DynamicArrayForLongContractJson,
    "",
    "4ace1748914470bca8f946094834338fb033b04ca4d7df2a176844e5750ec536"
  )
);

// Use this class to interact with the blockchain
export class DynamicArrayForLongInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<DynamicArrayForLongTypes.State> {
    return fetchContractState(DynamicArrayForLong, this);
  }

  methods = {
    get: async (
      params: DynamicArrayForLongTypes.CallMethodParams<"get">
    ): Promise<DynamicArrayForLongTypes.CallMethodResult<"get">> => {
      return callMethod(
        DynamicArrayForLong,
        this,
        "get",
        params,
        getContractByCodeHash
      );
    },
    update: async (
      params: DynamicArrayForLongTypes.CallMethodParams<"update">
    ): Promise<DynamicArrayForLongTypes.CallMethodResult<"update">> => {
      return callMethod(
        DynamicArrayForLong,
        this,
        "update",
        params,
        getContractByCodeHash
      );
    },
    push: async (
      params: DynamicArrayForLongTypes.CallMethodParams<"push">
    ): Promise<DynamicArrayForLongTypes.CallMethodResult<"push">> => {
      return callMethod(
        DynamicArrayForLong,
        this,
        "push",
        params,
        getContractByCodeHash
      );
    },
    pop: async (
      params: DynamicArrayForLongTypes.CallMethodParams<"pop">
    ): Promise<DynamicArrayForLongTypes.CallMethodResult<"pop">> => {
      return callMethod(
        DynamicArrayForLong,
        this,
        "pop",
        params,
        getContractByCodeHash
      );
    },
    sum: async (
      params: DynamicArrayForLongTypes.CallMethodParams<"sum">
    ): Promise<DynamicArrayForLongTypes.CallMethodResult<"sum">> => {
      return callMethod(
        DynamicArrayForLong,
        this,
        "sum",
        params,
        getContractByCodeHash
      );
    },
  };

  async multicall<Calls extends DynamicArrayForLongTypes.MultiCallParams>(
    calls: Calls
  ): Promise<DynamicArrayForLongTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      DynamicArrayForLong,
      this,
      calls,
      getContractByCodeHash
    )) as DynamicArrayForLongTypes.MultiCallResults<Calls>;
  }
}
