/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as AwesomeNFTCollectionContractJson } from "../AwesomeNFTCollection.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";

// Custom types for the contract
export namespace AwesomeNFTCollectionTypes {
  export type Fields = {
    nftTemplateId: HexString;
    collectionUri: HexString;
    totalSupply: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getCollectionUri: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    totalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    nftByIndex: {
      params: CallContractParams<{ index: bigint }>;
      result: CallContractResult<HexString>;
    };
    validateNFT: {
      params: CallContractParams<{ nftId: HexString; nftIndex: bigint }>;
      result: CallContractResult<null>;
    };
    mint: {
      params: CallContractParams<{ nftUri: HexString }>;
      result: CallContractResult<HexString>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getCollectionUri: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    totalSupply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    nftByIndex: {
      params: SignExecuteContractMethodParams<{ index: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    validateNFT: {
      params: SignExecuteContractMethodParams<{
        nftId: HexString;
        nftIndex: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    mint: {
      params: SignExecuteContractMethodParams<{ nftUri: HexString }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  AwesomeNFTCollectionInstance,
  AwesomeNFTCollectionTypes.Fields
> {
  encodeFields(fields: AwesomeNFTCollectionTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  consts = {
    ErrorCodes: {
      IncorrectTokenIndex: BigInt("0"),
      NFTNotFound: BigInt("1"),
      NFTNotPartOfCollection: BigInt("2"),
    },
  };

  at(address: string): AwesomeNFTCollectionInstance {
    return new AwesomeNFTCollectionInstance(address);
  }

  tests = {
    getCollectionUri: async (
      params: Omit<
        TestContractParamsWithoutMaps<AwesomeNFTCollectionTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(
        this,
        "getCollectionUri",
        params,
        getContractByCodeHash
      );
    },
    totalSupply: async (
      params: Omit<
        TestContractParamsWithoutMaps<AwesomeNFTCollectionTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "totalSupply", params, getContractByCodeHash);
    },
    nftByIndex: async (
      params: TestContractParamsWithoutMaps<
        AwesomeNFTCollectionTypes.Fields,
        { index: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "nftByIndex", params, getContractByCodeHash);
    },
    validateNFT: async (
      params: TestContractParamsWithoutMaps<
        AwesomeNFTCollectionTypes.Fields,
        { nftId: HexString; nftIndex: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "validateNFT", params, getContractByCodeHash);
    },
    mint: async (
      params: TestContractParamsWithoutMaps<
        AwesomeNFTCollectionTypes.Fields,
        { nftUri: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "mint", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: AwesomeNFTCollectionTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const AwesomeNFTCollection = new Factory(
  Contract.fromJson(
    AwesomeNFTCollectionContractJson,
    "",
    "86f278d2de249eca00d0c68f12167da0c1a54c02eaa8c148f89e659ae7cf11af",
    []
  )
);
registerContract(AwesomeNFTCollection);

// Use this class to interact with the blockchain
export class AwesomeNFTCollectionInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<AwesomeNFTCollectionTypes.State> {
    return fetchContractState(AwesomeNFTCollection, this);
  }

  view = {
    getCollectionUri: async (
      params?: AwesomeNFTCollectionTypes.CallMethodParams<"getCollectionUri">
    ): Promise<
      AwesomeNFTCollectionTypes.CallMethodResult<"getCollectionUri">
    > => {
      return callMethod(
        AwesomeNFTCollection,
        this,
        "getCollectionUri",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    totalSupply: async (
      params?: AwesomeNFTCollectionTypes.CallMethodParams<"totalSupply">
    ): Promise<AwesomeNFTCollectionTypes.CallMethodResult<"totalSupply">> => {
      return callMethod(
        AwesomeNFTCollection,
        this,
        "totalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    nftByIndex: async (
      params: AwesomeNFTCollectionTypes.CallMethodParams<"nftByIndex">
    ): Promise<AwesomeNFTCollectionTypes.CallMethodResult<"nftByIndex">> => {
      return callMethod(
        AwesomeNFTCollection,
        this,
        "nftByIndex",
        params,
        getContractByCodeHash
      );
    },
    validateNFT: async (
      params: AwesomeNFTCollectionTypes.CallMethodParams<"validateNFT">
    ): Promise<AwesomeNFTCollectionTypes.CallMethodResult<"validateNFT">> => {
      return callMethod(
        AwesomeNFTCollection,
        this,
        "validateNFT",
        params,
        getContractByCodeHash
      );
    },
    mint: async (
      params: AwesomeNFTCollectionTypes.CallMethodParams<"mint">
    ): Promise<AwesomeNFTCollectionTypes.CallMethodResult<"mint">> => {
      return callMethod(
        AwesomeNFTCollection,
        this,
        "mint",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getCollectionUri: async (
      params: AwesomeNFTCollectionTypes.SignExecuteMethodParams<"getCollectionUri">
    ): Promise<
      AwesomeNFTCollectionTypes.SignExecuteMethodResult<"getCollectionUri">
    > => {
      return signExecuteMethod(
        AwesomeNFTCollection,
        this,
        "getCollectionUri",
        params
      );
    },
    totalSupply: async (
      params: AwesomeNFTCollectionTypes.SignExecuteMethodParams<"totalSupply">
    ): Promise<
      AwesomeNFTCollectionTypes.SignExecuteMethodResult<"totalSupply">
    > => {
      return signExecuteMethod(
        AwesomeNFTCollection,
        this,
        "totalSupply",
        params
      );
    },
    nftByIndex: async (
      params: AwesomeNFTCollectionTypes.SignExecuteMethodParams<"nftByIndex">
    ): Promise<
      AwesomeNFTCollectionTypes.SignExecuteMethodResult<"nftByIndex">
    > => {
      return signExecuteMethod(
        AwesomeNFTCollection,
        this,
        "nftByIndex",
        params
      );
    },
    validateNFT: async (
      params: AwesomeNFTCollectionTypes.SignExecuteMethodParams<"validateNFT">
    ): Promise<
      AwesomeNFTCollectionTypes.SignExecuteMethodResult<"validateNFT">
    > => {
      return signExecuteMethod(
        AwesomeNFTCollection,
        this,
        "validateNFT",
        params
      );
    },
    mint: async (
      params: AwesomeNFTCollectionTypes.SignExecuteMethodParams<"mint">
    ): Promise<AwesomeNFTCollectionTypes.SignExecuteMethodResult<"mint">> => {
      return signExecuteMethod(AwesomeNFTCollection, this, "mint", params);
    },
  };

  async multicall<Calls extends AwesomeNFTCollectionTypes.MultiCallParams>(
    calls: Calls
  ): Promise<AwesomeNFTCollectionTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends AwesomeNFTCollectionTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<AwesomeNFTCollectionTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | AwesomeNFTCollectionTypes.MultiCallParams
      | AwesomeNFTCollectionTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      AwesomeNFTCollection,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
