/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { default as DepositAirdropScriptJson } from "../DepositAirdrop.ral.json";
import { default as DisperseAirdrop10ScriptJson } from "../DisperseAirdrop10.ral.json";
import { default as DisperseAirdrop25ScriptJson } from "../DisperseAirdrop25.ral.json";

export const DepositAirdrop = new ExecutableScript<{
  airdrop: HexString;
  tokenId: HexString;
  amount: bigint;
}>(Script.fromJson(DepositAirdropScriptJson));
export const DisperseAirdrop10 = new ExecutableScript<{
  airdrop: HexString;
  tokenId: HexString;
  amountPerAddress: bigint;
}>(Script.fromJson(DisperseAirdrop10ScriptJson));
export const DisperseAirdrop25 = new ExecutableScript<{
  airdrop: HexString;
  tokenId: HexString;
  amountPerAddress: bigint;
}>(Script.fromJson(DisperseAirdrop25ScriptJson));
