/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as TokenToBeLockedContractJson } from "../TokenToBeLocked.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";

// Custom types for the contract
export namespace TokenToBeLockedTypes {
  export type State = Omit<ContractState<any>, "fields">;

  export interface CallMethodTable {
    lockTokens: {
      params: CallContractParams<{
        recipient: Address;
        amount: bigint;
        till: bigint;
      }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    lockTokens: {
      params: SignExecuteContractMethodParams<{
        recipient: Address;
        amount: bigint;
        till: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<TokenToBeLockedInstance, {}> {
  encodeFields() {
    return encodeContractFields({}, this.contract.fieldsSig, []);
  }

  at(address: string): TokenToBeLockedInstance {
    return new TokenToBeLockedInstance(address);
  }

  tests = {
    lockTokens: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          never,
          { recipient: Address; amount: bigint; till: bigint }
        >,
        "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "lockTokens", params, getContractByCodeHash);
    },
  };

  stateForTest(initFields: {}, asset?: Asset, address?: string) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const TokenToBeLocked = new Factory(
  Contract.fromJson(
    TokenToBeLockedContractJson,
    "",
    "e8e6cac2676e02d58337b1ceddc4754544bf37c8d41aeeda1c44ad348f969a7b",
    []
  )
);
registerContract(TokenToBeLocked);

// Use this class to interact with the blockchain
export class TokenToBeLockedInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<TokenToBeLockedTypes.State> {
    return fetchContractState(TokenToBeLocked, this);
  }

  view = {
    lockTokens: async (
      params: TokenToBeLockedTypes.CallMethodParams<"lockTokens">
    ): Promise<TokenToBeLockedTypes.CallMethodResult<"lockTokens">> => {
      return callMethod(
        TokenToBeLocked,
        this,
        "lockTokens",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    lockTokens: async (
      params: TokenToBeLockedTypes.SignExecuteMethodParams<"lockTokens">
    ): Promise<TokenToBeLockedTypes.SignExecuteMethodResult<"lockTokens">> => {
      return signExecuteMethod(TokenToBeLocked, this, "lockTokens", params);
    },
  };
}
