/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as GaslessContractJson } from "../Gasless.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";

// Custom types for the contract
export namespace GaslessTypes {
  export type State = Omit<ContractState<any>, "fields">;

  export interface CallMethodTable {
    payGas: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    payNoGas: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    payGas: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    payNoGas: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<GaslessInstance, {}> {
  encodeFields() {
    return encodeContractFields({}, this.contract.fieldsSig, []);
  }

  at(address: string): GaslessInstance {
    return new GaslessInstance(address);
  }

  tests = {
    payGas: async (
      params?: Omit<
        TestContractParamsWithoutMaps<never, never>,
        "args" | "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "payGas",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    payNoGas: async (
      params?: Omit<
        TestContractParamsWithoutMaps<never, never>,
        "args" | "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "payNoGas",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  stateForTest(initFields: {}, asset?: Asset, address?: string) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const Gasless = new Factory(
  Contract.fromJson(
    GaslessContractJson,
    "",
    "75b46334b2d7a60b498b7ad575c33d83419c3541021948498214f966a87784e4",
    []
  )
);
registerContract(Gasless);

// Use this class to interact with the blockchain
export class GaslessInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<GaslessTypes.State> {
    return fetchContractState(Gasless, this);
  }

  view = {
    payGas: async (
      params?: GaslessTypes.CallMethodParams<"payGas">
    ): Promise<GaslessTypes.CallMethodResult<"payGas">> => {
      return callMethod(
        Gasless,
        this,
        "payGas",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    payNoGas: async (
      params?: GaslessTypes.CallMethodParams<"payNoGas">
    ): Promise<GaslessTypes.CallMethodResult<"payNoGas">> => {
      return callMethod(
        Gasless,
        this,
        "payNoGas",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    payGas: async (
      params: GaslessTypes.SignExecuteMethodParams<"payGas">
    ): Promise<GaslessTypes.SignExecuteMethodResult<"payGas">> => {
      return signExecuteMethod(Gasless, this, "payGas", params);
    },
    payNoGas: async (
      params: GaslessTypes.SignExecuteMethodParams<"payNoGas">
    ): Promise<GaslessTypes.SignExecuteMethodResult<"payNoGas">> => {
      return signExecuteMethod(Gasless, this, "payNoGas", params);
    },
  };
}
